name: num_game
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev
publish_to: 'none'

# Version info
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  math_expressions: ^2.2.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  intl: ^0.18.1  # ✅ For date formatting
  flutter_bloc: ^8.1.3  # ✅ Added for state management (Cubit/BLoC)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: OpenSans Regular
  #     fonts:
  #       - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
  #   - family: OpenSans Bold Italic
  #     fonts:
  #       - asset: assets/fonts/OpenSans/OpenSans_Condensed-BoldItalic.ttf
  #   - family: OpenSans Bold
  #     fonts:
  #       - asset: assets/fonts/OpenSans/OpenSans_Condensed-Bold.ttf
  #   - family: OpenSans Italic
  #     fonts:
  #       - asset: assets/fonts/OpenSans/OpenSans-Italic.ttf
  #   - family: Raleway Bold
  #     fonts:
  #       - asset: assets/fonts/Raleway/Raleway-Bold.ttf
  #   - family: Raleway Semi Bold
  #     fonts:
  #       - asset: assets/fonts/Raleway/Raleway-SemiBold.ttf
